name: WorldCleaner
version: '1.0-SNAPSHOT'
main: winlyps.worldCleaner.WorldCleaner
api-version: '1.16'
author: [Winlyps]
commands:
  dustman:
    description: Opens the collected items inventory.
    permission: worldcleaner.dustman
    usage: /dustman
permissions:
  worldcleaner.dustman:
    description: Allows the player to use the /dustman command.
    default: op
